In [33]:
# External packages:
try:
    import cPickle as pickle  # cPickle is faster, but not as complete
    
except:
    import pickle

import math
import datetime
import numpy as np
import pandas as pd

from sklearn import metrics
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.model_selection import train_test_split

In [15]:
class CHWForecasting:
    
    def CHWForecasting(self, model_file = None):
        """Creates a chilled water forcasting object. Loads an earlier model from file if 'model_file' is specified."""
        self._hourly_model = None
        self._daily_model = None
        self._hrs_before = None
        self._hrs_after = None
        self._days_before = None
        self._days_after = None
        self._daily_significance = None
        
        if model_file is not None:
            # Unpickle here...
            self.load(model_file)
    
    def build_hourly_model(self, hourly_power, hourly_weather, hrs_before, hrs_after):
        """
        Build and train model using 'hourly power' and 'hourly weather' as training data.
        
        Use hrs_before and hrs_after to specify the range data should be windowed to. hrs_after should match the 
        numbers of hours the future preditions will be made on.
        """
        hourly = pd.merge(hourly_power, hourly_weather, on = 'DATE')
        hourly['DATE'] = hourly.apply(lambda x: pd.Timestamp(x['DATE']), axis=1)
        
        past_features = hourly.columns.tolist()
        past_features.remove('DATE')
        
        future_features = hourly_weather.columns.tolist()
        future_features.remove('DATE')

        #past_features = ['Total Power (trimmed)', 'HourlyDryBulbTemperature', 'HourlyWetBulbTemperature']
        #future_features = ['HourlyDryBulbTemperature', 'HourlyWetBulbTemperature']

        hourlyWindowed = self.windowData(hourly, npast = hrs_before, nfuture = hrs_after, colpast = past_features, colfuture = future_features)
        hourlyWindowed = self.genTSfeats(windowedDF = hourlyWindowed, windows = [22])  
        hourlyWindowed = self.addTimeFeatures(hourlyWindowed)
        X, Ys = self.genXY(hourlyWindowed, 'Total Power (trimmed)', maxoffset = hrs_after)
        
        all_model = []
        all_rmse = []
        
        for Y in Ys:
            model, mae, rmse, rsq = self.runModel(X, Y, model=ExtraTreesRegressor())
            all_model.append(model)
            all_rmse.append(rmse)
        
        self._hourly_model = [all_model, all_rmse]
        
        return self._hourly_model
    
    def build_daily_model(self, hourly_power, hourly_weather, days_before, days_after, significance = 0.85):
        """
        Build and train model using 'hourly power' and 'hourly weather' as training data.
        
        Use hrs_before and hrs_after to specify the range data should be windowed to. hrs_after should match the 
        numbers of hours in the future preditions will be made on.
        """
        train = pd.merge(hourly_power, hourly_weather, on = "DATE")
        self._daily_significance = significance
        self._daily_model = trainGB_ndays(train, signficance = significance)
        
    def trainGB_ndays(df, predictorVar = 'Total Power (trimmed)_max', dropCols = ['DATE'], significance = 0.85):
        gb_modelList = []
        for i in range(5):
            days = i+1
            dailyMaxModels = trainGB_Model(df, days, predictorVar, dropCols, significance) 
            gb_modelList.append(dailyMaxModels)

        return gb_modelList
    
    def predict_hourly_forecast(self, date_and_time, recent_power, recent_weather, forecasted_weather):
        """ Creates a forecast object for this class using provided data to give predictions. """
        
        recent = pd.merge(recent_power, recent_weather, on = 'DATE')
        
        past_features = recent.columns.tolist()
        past_features.remove('DATE')
    
        future_features = forecasted_weather.columns.tolist()
        future_features.remove('DATE')
        
        merged = recent.append(forecasted_weather, sort = False)
        merged["DATE"] = merged.apply(lambda x: pd.Timestamp(x["DATE"]), axis=1)
        merged.reset_index()
        
        windowed = self.windowData(merged, npast = len(recent_power)-1, nfuture = len(forecasted_weather)-1, colpast = past_features, colfuture = future_features)
        windowed_ts = self.genTSfeats(windowedDF = windowed, windows = [22])
        self.addTimeFeatures(windowed_ts)
        
        df = windowed_ts.dropna()
        df = df.drop(columns = ['DATE'])
        
        all_pred = []

        for m in self._hourly_model[0]:
            all_pred.append(m.predict(df))
        
        #max_power = max(all_pred) # peak power (tons)
        #peak_future_hour = all_pred.index(max_power) 
        #max_power_error = self._hourly_model[1][peak_future_hour] 
        #pred_int = (max_power[0] - (2*max_power_error), max_power[0] + (2*max_power_error)) 
        
        #current_date_and_time = pd.to_datetime(date_and_time) # assuming date_and_time gets passed in as a string in the form 'MM-DD-YYYY HH:MM:SS'
        #hours_to_add = datetime.timedelta(hours = peak_future_hour + 1)
        #peak_timestamp = current_date_and_time + hours_to_add
        
        #return max_power, peak_timestamp, pred_int
        return all_pred
    
    def predict_daily_forecast(self, recent_power, recent_weather, forecasted_weather):
        """Creates a forecast object for this class using provided data to give predictions."""
        predictDf = pd.merge(recent_power, recent_weather.append(forecasted_weather), on = 'DATE', how ='outer')
        return predict(predictDF, nDays = len(forecasted_weather.index), self._daily_model)
        
    def predict(df, nDays, modelList):
        test = prepPredict(df, nDays)
        date = test['DATE']
        testDf = pd.DataFrame(test.values.reshape(1,-1) , columns = test.index)

        X = testDf.drop(columns = ['DATE', 'Total Power (trimmed)_max'])

        lower = modelList[nDays - 1][0].predict(X)[0]
        mid = modelList[nDays - 1][1].predict(X)[0]
        upper = modelList[nDays - 1][2].predict(X)[0]

        return lower, mid, upper, date
    
    def windowData(self, df, npast=0, nfuture=0, colpast=[], colfuture=[]):
    
        # Add past windows:
        kept_past = df[colpast]  # elements used in past windows...
        for i in range(1, npast+1):
            temp = kept_past.shift(i)
            temp.columns = [f"{c}-{i}hr" for c in kept_past.columns]
            df = pd.concat([df,temp], axis=1)
        
        # Add future windows:
        kept_future = df[colfuture]  # elements used future windows...
        for i in range(1, nfuture+1):
            temp = kept_future.shift(-i)
            temp.columns = [f"{c}+{i}hr" for c in kept_future.columns]
            df = pd.concat([df,temp], axis=1)
    
        return df
    
    def genTSfeats(self, windowedDF, windows = []): 

        for win in windows: # Loop over windows of different sizes, if passed--22 is optimal.

            # Generate temporary 'lookback' dataframes for feature construction:
            tmp_power = windowedDF.iloc[:, 4:(3*win)+4:3]
            tmp_drybulb = windowedDF.iloc[:, 5:(3*win)+5:3]
            tmp_wetbulb = windowedDF.iloc[:, 6:(3*win)+6:3]

            tmp_dfs = [tmp_power, tmp_drybulb, tmp_wetbulb]
            var_names = ['power', 'drybulb', 'wetbulb']

            # Loop over temporary dataframes and construct desired features:
            for tmp, var in zip(tmp_dfs, var_names):
                
                # General statistics for base level.
                windowedDF[f'meanprev{win}_{var}'] = tmp.mean(axis=1)
                windowedDF[f'medianprev{win}_{var}'] = tmp.median(axis=1)
                windowedDF[f'minprev{win}_{var}'] = tmp.min(axis=1)
                windowedDF[f'maxprev{win}_{var}'] = tmp.max(axis=1)
                windowedDF[f'stdprev{win}_{var}'] = tmp.std(axis=1)

                # Capturing trend.
                windowedDF[f'mean_ewmprev{win}_{var}'] = tmp.T.ewm(com=9.5).mean().T.mean(axis=1)
                windowedDF[f'last_ewmprev{win}_{var}'] = tmp.T.ewm(com=9.5).mean().T.iloc[:,-1]
                windowedDF[f'avgdiff{win}_{var}'] = (tmp - tmp.shift(1, axis=1)).mean(axis=1)

        return windowedDF
    
    def addTimeFeatures(self, df):
        
        # Month:
        months = df.apply(lambda x: x["DATE"].month, axis=1)
        df['month_sin'] = np.sin((months-1)*(2.*np.pi/12))
        df['month_cos'] = np.cos((months-1)*(2.*np.pi/12))

        # Day of Week:
        dow = df.apply(lambda x: x["DATE"].dayofweek, axis=1)
        df['DoW_sin'] = np.sin(dow*(2.*np.pi/7))
        df['DoW_cos'] = np.cos(dow*(2.*np.pi/7))

        # Hour of Day:
        hr = df.apply(lambda x: x["DATE"].hour, axis=1)
        df['Hour_sin'] = np.sin(hr*(2.*np.pi/24))
        df['Hour_cos'] = np.cos(hr*(2.*np.pi/24))
        
        return df
    
    def genXY(self, X, target_var, maxoffset = 1):
        '''
        Generate X and Y data to be used in run model. X should be untrimmed (include NaNs).
        Will return tuple contianing trimmed X and list of Y vectors with offset ranging from 1 to maxoffset.
        '''
        df = X.copy()
        Y = []

        for l in range(1, maxoffset+1):
            df[f"offset_{l}"] = df[target_var].shift(-l)

        df = df.dropna()
        df = df.reset_index(drop = True)
        df = df.drop(columns = ['DATE'])

        for l in range(1, maxoffset+1):
            Y.append(df[f"offset_{l}"])
            df.drop(columns=[f"offset_{l}"], inplace = True)

        return (df, Y)
    
    def runModel(self, X, Y, model, verbose=False):

        X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.8, random_state = 12345, shuffle = True)  # Create train & test sets.
        model.fit(X_train, Y_train)  # Fit model...

        # Calculate error metrics:
        rsq = model.score(X_test, Y_test)
        rmse = math.sqrt(metrics.mean_squared_error(Y_test, model.predict(X_test)))
        mae = metrics.mean_absolute_error(Y_test, model.predict(X_test))

        # Display if selected in arguments:
        if verbose:
            print("R Squared Score: {:.4f}".format(rsq))
            print("Root Mean Squared Error: {:.2f}".format(rmse))
            print("Mean Absolute Error: {:.2f}".format(mae))

        return model, mae, rmse, rsq
    
    def formatTrainingData(df, trainDays = 7, nDays = 1):
    
        df["DATE"] = df.apply(lambda x: pd.Timestamp(x["DATE"]), axis=1)
        df['DATE'] = [d.date() for d in df["DATE"]]

        groupby = df.groupby('DATE').describe()

        colList = df.drop(columns = ['DATE']).columns
        parameters = ['min', 'max', 'mean']

        dailyData = {'DATE':list(groupby.index)}

        nday_cols = []
        for i in range(len(colList)):
            if(i == 0):
                dailyData['Total Power (trimmed)_max'] = list(groupby[colList[i]]['max'])
            else:                                     
                for param in parameters:
                    colname = colList[i] + "_" + param
                    dailyData[colList[i] + "_" + param] = list(groupby[colList[i]][param])
                    nday_cols.append(colname)

        daily = pd.DataFrame(dailyData)

        daily['weekday'] = [row['DATE'].weekday() for i, row in daily.iterrows()]
        if(nDays > 0):
            for col in nday_cols:
                for i in range(nDays + trainDays):
                    colname = col + "-" + str(i + 1) + "day"
                    daily[colname] = daily[col].shift(i+1)

            for col in ['Total Power (trimmed)_max']:#, 'Total Power (trimmed)_avg']:
                for i in range(nDays, trainDays + nDays + 1):
                    colname = col + "-" + str(i) + "day"
                    daily[colname] = daily[col].shift(i)

        addTimeFeatures(daily)

        daily = daily.dropna()
        return daily
    
    def trainGB_Model(df, days, predictorVar, dropCols, significance):
        dropCols.append(predictorVar)

        daily = formatTrainingData(df, nDays = days)

        # Set lower and upper quantile
        LOWER_ALPHA = (1 - significance)/2
        UPPER_ALPHA = 1-LOWER_ALPHA

        # Each model has to be separate
        lower = GradientBoostingRegressor(loss="quantile",                   
                                                alpha=LOWER_ALPHA)
        # The mid model will use the default loss
        mid = GradientBoostingRegressor(loss="ls")

        upper = GradientBoostingRegressor(loss="quantile",
                                                alpha=UPPER_ALPHA)
        X = daily.drop(dropCols, axis=1)
        Y = daily[predictorVar]

        #train the 3 models separately
        lower.fit(X, Y)
        mid.fit(X, Y)
        upper.fit(X, Y)

        return [lower, mid, upper]
    
    def prepPredict(df, nDays, trainDays = 7):

        df["DATE"] = df.apply(lambda x: pd.Timestamp(x["DATE"]), axis=1)
        df['DATE'] = [d.date() for d in df["DATE"]]

        for index in range(len(df)):
            if(df.loc[index]['Total Power (trimmed)_max'] != df.loc[index]['Total Power (trimmed)_max']):
                today = index-1
                predictDay = today + nDays
                break
        #print(today)

        testDf = df.copy()

        if(nDays > 0):
            for col in testDf.columns[2:]:
                for i in range(nDays + trainDays):
                    colname = col + "-" + str(i + 1) + "day"
                    testDf[colname] = testDf[col].shift(i+1)

            powerCol = testDf.columns[1]
            for i in range(nDays, trainDays + nDays + 1):
                colname = powerCol + "-" + str(i) + "day"
                testDf[colname] = testDf[powerCol].shift(i)

        testDf['weekday'] = [row['DATE'].weekday() for i, row in testDf.iterrows()]
        addTimeFeatures(testDf)

        return testDf.loc[predictDay]

    # load and save are untested, should work though
    # https://stackoverflow.com/questions/2709800/how-to-pickle-yourself
    
    def load(self, filename):
        """  """
        f = open(filename, 'rb')
        tmp_dict = pickle.load(f)
        f.close()          
        self.__dict__.clear()
        self.__dict__.update(tmp_dict) 

    def save(self, filename):
        """  """
        f = open(filename, 'wb')
        pickle.dump(self.__dict__, f, 2)
        f.close()

In [27]:
# Try to ignore Forecast and return max powers and times within predict functions if possible
class Forecast:
    
    def Forecast(self, model_errors, predictions, time):
        self._model_errors = model_errors
        self._forecasted_power = predictions  # List of future predictions for each future hour
        self._init_time = time          # Time prediction was made from
    
    def get_next_max(self):
        """Returns time and value of next power maximum within 24 hrs"""
        max_power = max(self._forecasted_power) # peak power (tons)
        peak_future_hour = self._forecasted_power.index(max_power) 
        max_power_error = self._model_errors[peak_future_hour] 
        pred_int = (max_power[0] - (2*max_power_error), max_power[0] + (2*max_power_error)) 
        
        ## TO DO: Adjust based on how date gets passed in!
        current_date_and_time = pd.to_datetime(self._init_time) # assuming date_and_time gets passed in as a string in the form 'MM-DD-YYYY HH:MM:SS'
        hours_to_add = datetime.timedelta(hours = peak_future_hour + 1)
        peak_timestamp = current_date_and_time + hours_to_add
        return max_power, peak_timestamp, pred_int
    
    def get_daily_max(self):
        """Returns time and value of next power maximum for each 24 hrs in the forecast"""
        pass

In [ ]:
max_power = max(all_pred) # peak power (tons)
peak_future_hour = all_pred.index(max_power) 
max_power_error = self._hourly_model[1][peak_future_hour] 
pred_int = (max_power[0] - (2*max_power_error), max_power[0] + (2*max_power_error)) 
        
## TO DO: Adjust based on how date gets passed in!
current_date_and_time = pd.to_datetime(date_and_time) # assuming date_and_time gets passed in as a string in the form 'MM-DD-YYYY HH:MM:SS'
hours_to_add = datetime.timedelta(hours = peak_future_hour + 1)
peak_timestamp = current_date_and_time + hours_to_add

In [4]:
# Testing how to merge the hourly_power and hourly_weather data within build_hourly_model.
hourly_power = pd.read_csv('hourly_power.csv', index_col = 0)
hourly_weather = pd.read_csv('hourly_weather.csv', index_col = 0)

hourly = pd.merge(hourly_power, hourly_weather, on = 'DATE')
hourly

DATE  Total Power (trimmed)  HourlyWetBulbTemperature  \
0      2019-03-01 00:00:00               0.000000                      15.0   
1      2019-03-01 01:00:00               0.000000                      15.0   
2      2019-03-01 02:00:00               0.000000                      15.0   
3      2019-03-01 03:00:00               0.000000                      17.0   
4      2019-03-01 04:00:00               0.000000                      14.0   
...                    ...                    ...                       ...   
17543  2021-02-28 19:00:00            1365.385205                      40.0   
17544  2021-02-28 20:00:00            1396.574994                      39.0   
17545  2021-02-28 21:00:00            1397.580432                      39.0   
17546  2021-02-28 22:00:00            1398.621039                      39.0   
17547  2021-02-28 23:00:00            1392.329980                      40.0   

       HourlyDryBulbTemperature  
0                          17.0  
1                          17.0  
2                          17.0  
3                          19.0  
4                          16.0  
...                         ...  
17543                      43.0  
17544                      42.0  
17545                      42.0  
17546                      42.0  
17547                      43.0  

[17548 rows x 4 columns]

In [17]:
recent_power = pd.read_csv('recent_power_1.csv', index_col = 0)
recent_weather = pd.read_csv('recent_weather_1.csv', index_col = 0)
forecasted_weather = pd.read_csv('forecasted_weather_1.csv', index_col = 0)

In [18]:
forecast = CHWForecasting()

In [21]:
hourly_model_w_errors = forecast.build_hourly_model(hourly_power, hourly_weather, 24, 24)

In [23]:
predictions = forecast.predict_hourly_forecast('2020-04-20 17:00:00', recent_power, recent_weather, forecasted_weather)

In [29]:
forecast_1 = Forecast()

In [30]:
forecast_1.Forecast(hourly_model_w_errors[1], predictions, '2020-04-20 17:00:00')

In [31]:
forecast_1.get_next_max()

(array([3192.05078125]),
 Timestamp('2020-04-21 06:00:00'),
 (2293.3928040236274, 4090.7087584763726))

In [32]:
predictions

[array([2933.1640625]),
 array([2924.7671875]),
 array([2760.359375]),
 array([2605.6921875]),
 array([2594.7859375]),
 array([2592.7390625]),
 array([2586.4625]),
 array([2561.6203125]),
 array([2532.43125]),
 array([2541.915625]),
 array([2522.0015625]),
 array([2658.815625]),
 array([3192.05078125]),
 array([3183.471875]),
 array([2866.303125]),
 array([2817.9484375]),
 array([2618.559375]),
 array([2703.6421875]),
 array([2852.696875]),
 array([3027.65]),
 array([3028.6609375]),
 array([2768.790625]),
 array([2720.684375]),
 array([2686.134375])]

In [34]:
train_power = pd.read_csv('Build Model Data/hourly_power.csv')
train_weather = pd.read_csv('Build Model Data/hourly_weather.csv')

train = pd.merge(train_power, train_weather, on="DATE")
train

FileNotFoundError: [Errno 2] No such file or directory: 'Build Model Data/hourly_power.csv'